### ISSUE TITLE
browser stuck in redirection loop when adding allow_only = predicates.has_permission('something') to root controller

### ISSUE THREAD

**Issue by eteamin** [TurboGears/tg2#79]
by adding allow_only = predicates.has_permission('something') to the root controller, browser stucks in infinite redirection loop.

**Comment by amol-** [comment]
That's actually the expected behaviour. The predicate sends the user to `/login` page due to the authentication challenger, but the `login` action is implemented in `RootController` which has the predicate, so when the browser gets redirected to `/login` the predicate is rechecked and triggers again a redirection to `/login`.

Having an `allow_only` clause in `RootController` is generally not a very good idea as it will also prevent error pages from rendering

**Comment by eteamin** [comment]
thanks.
